// Code generated by go-swagger; DO NOT EDIT.

package buy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// BuyOKCode is the HTTP code returned for type BuyOK
const BuyOKCode int = 200

/*BuyOK OK

swagger:response buyOK
*/
type BuyOK struct {
}

// NewBuyOK creates BuyOK with default headers values
func NewBuyOK() *BuyOK {

	return &BuyOK{}
}

// WriteResponse to the client
func (o *BuyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// BuyUnauthorizedCode is the HTTP code returned for type BuyUnauthorized
const BuyUnauthorizedCode int = 401

/*BuyUnauthorized Пользователь не авторизован

swagger:response buyUnauthorized
*/
type BuyUnauthorized struct {
}

// NewBuyUnauthorized creates BuyUnauthorized with default headers values
func NewBuyUnauthorized() *BuyUnauthorized {

	return &BuyUnauthorized{}
}

// WriteResponse to the client
func (o *BuyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
