// Code generated by go-swagger; DO NOT EDIT.

package sales

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BuyHandlerFunc turns a function with the right signature into a buy handler
type BuyHandlerFunc func(BuyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BuyHandlerFunc) Handle(params BuyParams) middleware.Responder {
	return fn(params)
}

// BuyHandler interface for that can handle valid buy params
type BuyHandler interface {
	Handle(BuyParams) middleware.Responder
}

// NewBuy creates a new http.Handler for the buy operation
func NewBuy(ctx *middleware.Context, handler BuyHandler) *Buy {
	return &Buy{Context: ctx, Handler: handler}
}

/*Buy swagger:route GET /sales/{sale_id}/buy sales buy

Купить лот

*/
type Buy struct {
	Context *middleware.Context
	Handler BuyHandler
}

func (o *Buy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBuyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
