// Code generated by go-swagger; DO NOT EDIT.

package sales

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SalesListHandlerFunc turns a function with the right signature into a sales list handler
type SalesListHandlerFunc func(SalesListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SalesListHandlerFunc) Handle(params SalesListParams) middleware.Responder {
	return fn(params)
}

// SalesListHandler interface for that can handle valid sales list params
type SalesListHandler interface {
	Handle(SalesListParams) middleware.Responder
}

// NewSalesList creates a new http.Handler for the sales list operation
func NewSalesList(ctx *middleware.Context, handler SalesListHandler) *SalesList {
	return &SalesList{Context: ctx, Handler: handler}
}

/*SalesList swagger:route GET /sales sales salesList

Список лотов

*/
type SalesList struct {
	Context *middleware.Context
	Handler SalesListHandler
}

func (o *SalesList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSalesListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
