// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CancelHandlerFunc turns a function with the right signature into a cancel handler
type CancelHandlerFunc func(CancelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CancelHandlerFunc) Handle(params CancelParams) middleware.Responder {
	return fn(params)
}

// CancelHandler interface for that can handle valid cancel params
type CancelHandler interface {
	Handle(CancelParams) middleware.Responder
}

// NewCancel creates a new http.Handler for the cancel operation
func NewCancel(ctx *middleware.Context, handler CancelHandler) *Cancel {
	return &Cancel{Context: ctx, Handler: handler}
}

/*Cancel swagger:route GET /user/sales/{sale_id}/cancel user cancel

Отменить продажу

*/
type Cancel struct {
	Context *middleware.Context
	Handler CancelHandler
}

func (o *Cancel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCancelParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
