// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "trade-shop/pkg/models"
)

// CancelOKCode is the HTTP code returned for type CancelOK
const CancelOKCode int = 200

/*CancelOK OK

swagger:response cancelOK
*/
type CancelOK struct {
}

// NewCancelOK creates CancelOK with default headers values
func NewCancelOK() *CancelOK {

	return &CancelOK{}
}

// WriteResponse to the client
func (o *CancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CancelBadRequestCode is the HTTP code returned for type CancelBadRequest
const CancelBadRequestCode int = 400

/*CancelBadRequest Логическая ошибка

swagger:response cancelBadRequest
*/
type CancelBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewCancelBadRequest creates CancelBadRequest with default headers values
func NewCancelBadRequest() *CancelBadRequest {

	return &CancelBadRequest{}
}

// WithPayload adds the payload to the cancel bad request response
func (o *CancelBadRequest) WithPayload(payload *models.ErrorResult) *CancelBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel bad request response
func (o *CancelBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CancelUnauthorizedCode is the HTTP code returned for type CancelUnauthorized
const CancelUnauthorizedCode int = 401

/*CancelUnauthorized Пользователь не аутентифицирован в системе

swagger:response cancelUnauthorized
*/
type CancelUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewCancelUnauthorized creates CancelUnauthorized with default headers values
func NewCancelUnauthorized() *CancelUnauthorized {

	return &CancelUnauthorized{}
}

// WithPayload adds the payload to the cancel unauthorized response
func (o *CancelUnauthorized) WithPayload(payload *models.ErrorResult) *CancelUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel unauthorized response
func (o *CancelUnauthorized) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
