// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LogoutOKCode is the HTTP code returned for type LogoutOK
const LogoutOKCode int = 200

/*LogoutOK OK

swagger:response logoutOK
*/
type LogoutOK struct {
}

// NewLogoutOK creates LogoutOK with default headers values
func NewLogoutOK() *LogoutOK {

	return &LogoutOK{}
}

// WriteResponse to the client
func (o *LogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// LogoutUnauthorizedCode is the HTTP code returned for type LogoutUnauthorized
const LogoutUnauthorizedCode int = 401

/*LogoutUnauthorized Пользователь не авторизован

swagger:response logoutUnauthorized
*/
type LogoutUnauthorized struct {
}

// NewLogoutUnauthorized creates LogoutUnauthorized with default headers values
func NewLogoutUnauthorized() *LogoutUnauthorized {

	return &LogoutUnauthorized{}
}

// WriteResponse to the client
func (o *LogoutUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
