// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"net/http"

	uuid "github.com/satori/go.uuid"
)

type AuthService interface {
	GetUserAuth(r *http.Request) (*uuid.UUID, bool)
}
