// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import "trade-shop/pkg/store"

type Mailer interface {
	SendNotificationEmail(emailType string, to string, itemList []store.ItemSale) error
}
