// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"gopkg.in/boj/redistore.v1"
	"net/http"

	"github.com/gorilla/sessions"
)

type RediStore interface {
	// SetMaxLength sets RediStore.maxLength if the `l` argument is greater or equal 0
	// maxLength restricts the maximum length of new sessions to l.
	// If l is 0 there is no limit to the size of a session, use with caution.
	// The default for a new RediStore is 4096. Redis allows for max.
	// value sizes of up to 512MB (http://redis.io/topics/data-types)
	// Default: 4096,
	SetMaxLength(l int)
	// SetKeyPrefix set the prefix
	SetKeyPrefix(p string)
	// SetSerializer sets the serializer
	SetSerializer(ss redistore.SessionSerializer)
	// SetMaxAge restricts the maximum age, in seconds, of the session record
	// both in database and a browser. This is to change session storage configuration.
	// If you want just to remove session use your session `s` object and change it's
	// `Options.MaxAge` to -1, as specified in
	//    http://godoc.org/github.com/gorilla/sessions#Options
	//
	// Default is the one provided by this package value - `sessionExpire`.
	// Set it to 0 for no restriction.
	// Because we use `MaxAge` also in SecureCookie crypting algorithm you should
	// use this function to change `MaxAge` value.
	SetMaxAge(v int)
	// Close closes the underlying *redis.Pool
	Close() error
	// Get returns a session for the given name after adding it to the registry.
	//
	// See gorilla/sessions FilesystemStore.Get().
	Get(r *http.Request, name string) (*sessions.Session, error)
	// New returns a session for the given name without adding it to the registry.
	//
	// See gorilla/sessions FilesystemStore.New().
	New(r *http.Request, name string) (*sessions.Session, error)
	// Save adds a single session to the response.
	Save(r *http.Request, w http.ResponseWriter, session *sessions.Session) error
	// Delete removes the session from redis, and sets the cookie to expire.
	//
	// WARNING: This method should be considered deprecated since it is not exposed via the gorilla/sessions interface.
	// Set session.Options.MaxAge = -1 and call Save instead. - July 18th, 2013
	Delete(r *http.Request, w http.ResponseWriter, session *sessions.Session) error
}
