// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"trade-shop/pkg/models"

	uuid "github.com/satori/go.uuid"
)

type Sale interface {
	CreateLot(userID uuid.UUID, itemList []*models.ItemSale) error
	Purchase(userID uuid.UUID, sellerID uuid.UUID, saleID uuid.UUID) error
	MakeSalesList(userID uuid.UUID) []*models.Sale
	MakeUserSalesList(userID uuid.UUID) []*models.Sale
	Cancel(userID uuid.UUID, saleID uuid.UUID) error
}
