// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

import uuid "github.com/satori/go.uuid"

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GetUserAuth provides a mock function with given fields: r
func (_m *AuthService) GetUserAuth(r *http.Request) (*uuid.UUID, bool) {
	ret := _m.Called(r)

	var r0 *uuid.UUID
	if rf, ok := ret.Get(0).(func(*http.Request) *uuid.UUID); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*http.Request) bool); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
