// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import store "trade-shop/pkg/store"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendNotificationEmail provides a mock function with given fields: to, itemList
func (_m *Mailer) SendNotificationEmail(to string, itemList []*store.ItemSale) error {
	ret := _m.Called(to, itemList)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []*store.ItemSale) error); ok {
		r0 = rf(to, itemList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
